---
name: build (macOS ARM64)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake git autoconf automake libtool

      - name: Build Protobuf
        run: |
              git clone --branch v27.1 https://github.com/protocolbuffers/protobuf.git
              cd protobuf
              git submodule update --init --recursive
              mkdir build && cd build
              export CXXFLAGS=""
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/protobuf-install \
                -DCMAKE_CXX_STANDARD=23 \
                -DCMAKE_CXX_FLAGS="" \
                -DABSL_RANDOM_RANDEN_HWAES_IMPL_ENABLE_SSE4_1=OFF \
                -DABSL_ENABLE_SSE4_1=OFF \
                -DABSL_ENABLE_SSE2=OFF
              make -j$(sysctl -n hw.ncpu)
              make install

      - name: Build gRPC
        run: |
              git clone --branch v1.74.0 https://github.com/grpc/grpc.git
              cd grpc
              git submodule update --init --recursive
              mkdir -p build && cd build
              export PROTOBUF_DIR=$GITHUB_WORKSPACE/protobuf-install
              export CXXFLAGS=""
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DgRPC_PROTOBUF_PROVIDER=package \
                -DProtobuf_DIR=$PROTOBUF_DIR/lib/cmake/protobuf \
                -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/grpc-install \
                -DCMAKE_CXX_STANDARD=23 \
                -DCMAKE_CXX_FLAGS="" \
                -DABSL_RANDOM_RANDEN_HWAES_IMPL_ENABLE_SSE4_1=OFF \
                -DABSL_ENABLE_SSE4_1=OFF \
                -DABSL_ENABLE_SSE2=OFF
              make -j$(sysctl -n hw.ncpu)
              make install

      - name: Package libraries
        run: |
          tar czvf grpc-protobuf-macos-arm64-${{ github.ref_name }}.tar.gz \
            -C $GITHUB_WORKSPACE/grpc-install . \
            -C $GITHUB_WORKSPACE/protobuf-install .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: grpc-protobuf-macos-arm64-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for workflow dispatch
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: grpc-protobuf-macos-arm64
          path: grpc-protobuf-macos-arm64-${{ github.ref_name }}.tar.gz
