---
name: Build gRPC & Protobuf C++ (Windows)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake git

      - name: Build Protobuf
        run: |
          git clone --branch v21.6 `
            https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE\protobuf-install
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Build gRPC
        run: |
          git clone --branch v1.75.0 https://github.com/grpc/grpc.git
          cd grpc
          git submodule update --init --recursive
          mkdir build
          cd build
          $protobufDir = "$env:GITHUB_WORKSPACE\protobuf-install"
          cmake .. -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DgRPC_PROTOBUF_PROVIDER=package `
            -DProtobuf_DIR=$protobufDir\lib\cmake\protobuf `
            -DCMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE\grpc-install
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Package libraries
        run: |
          Compress-Archive -Path `
            $env:GITHUB_WORKSPACE\grpc-install\*, `
            $env:GITHUB_WORKSPACE\protobuf-install\* `
            -DestinationPath grpc-protobuf-windows-${{ github.ref_name }}.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: grpc-protobuf-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for workflow dispatch
        uses: actions/upload-artifact@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          name: grpc-protobuf-windows
          path: grpc-protobuf-windows-${{ github.ref_name }}.zip
