name: Build gRPC & Protobuf C++ (Windows)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake git

      - name: Build Protobuf
        run: |
          git clone --branch v21.6 https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --install . --prefix $env:GITHUB_WORKSPACE\protobuf-out

      - name: Build gRPC
        run: |
          git clone --branch v1.75.0 https://github.com/grpc/grpc.git
          cd grpc
          git submodule update --init --recursive
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DgRPC_PROTOBUF_PROVIDER=package -DProtobuf_DIR=$env:GITHUB_WORKSPACE\protobuf-out\lib\cmake\protobuf
          cmake --build . --config Release
          cmake --install . --prefix $env:GITHUB_WORKSPACE\grpc-out

      - name: Package libraries
        run: |
          Compress-Archive -Path $env:GITHUB_WORKSPACE\grpc-out\*,$env:GITHUB_WORKSPACE\protobuf-out\* -DestinationPath grpc-protobuf-windows.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: grpc-protobuf-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
