---
name: build (Windows)

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
        - name: Build and extract artifact
          run: |
            make build-windows

        - name: Upload release asset
          uses: softprops/action-gh-release@v1
          if: github.event_name == 'release'
          with:
            files: grpc-protobuf-windows.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload artifact for workflow dispatch
          uses: actions/upload-artifact@v4
          if: github.event_name == 'workflow_dispatch'
          with:
            name: grpc-protobuf-windows
            path: grpc-protobuf-windows.zip
